---

- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    foo_initial_value: ["foo_initial"]
    a__foo_list: ["foo1", "foo2"]
    b__foo_list: ["foo3", "foo4"]

    bar_initial_value: ["bar_initial"]
    a__bar_list: ["bar1", "bar2"]
    b__bar_list: ["bar3", "bar4"]

    #_foo_merged: "{{ (lookup('vars', *query('varnames', '^.+__foo_list$')) + [foo_initial_value]) | flatten(levels=1) }}"
    #_foo_merged: "{% import 'merge_macro.j2' %}{{ merge_macro('__foo_list', foo_initial_value) }}"
    _bar_merged: "{{ (lookup('vars', *query('varnames', '^.+__bar_list$')) + [bar_initial_value]) | flatten(levels=1) }}"

  tasks:
    - name: Print _foo_merged
      debug:
        msg: "{% import 'merge_macro.j2' %}{{ merge_macro('__foo_list', foo_initial_value) }}"
        #msg: "{{ _foo_merged }}"

    - name: Print _bar_merged
      debug:
        msg: "{{ _bar_merged }}"
